import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().min(1),
    DATABASE_PASSWORD: z.string().min(1),
    NEXT_PUBLIC_APP_URL: z.string().url(),
    FROM_EMAIL: z.string().min(1),
    FROM_EMAIL_PASSWORD: z.string().min(1),
    SMTP_SERVER: z.string().min(1),
    FROM_EMAIL_GMAIL: z.string().min(1),
    SMTP_PORT: z.string().min(1),
    AUTH_URL: z.string().url(),
    AUTH_SECRET: z.string().min(1),
    GROQ_API_KEY: z.string().min(1),
    GROQ_API_ENDPOINT: z.string().min(1),
    UNDRSTND_API_KEY: z.string().min(1),
    UNDRSTND_API_ENDPOINT: z.string().min(1),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    GR_LPU_API_KEY_DEFAULT: z.string().min(1),
    CR_INF_API_KEY_DEFAULT: z.string().min(1),
    SM_RDU_API_KEY_DEFAULT: z.string().min(1),
    NODE_ENV: z.string().min(1),
    PINECONE_API_KEY: z.string().min(1),
    PINECONE_API_ENDPOINT: z.string().min(1),
    OPENAI_API_KEY: z.string().min(1),
    NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1),
    GITHUB_CLIENT_ID: z.string().min(1),
    GITHUB_CLIENT_SECRET: z.string().min(1),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().url(),
    NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1),
  },
  runtimeEnv: {
    DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
    DATABASE_URL: process.env.DATABASE_URL,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    FROM_EMAIL: process.env.FROM_EMAIL,
    FROM_EMAIL_GMAIL: process.env.FROM_EMAIL_GMAIL,
    SMTP_PORT: process.env.SMTP_PORT,
    FROM_EMAIL_PASSWORD: process.env.FROM_EMAIL_PASSWORD,
    SMTP_SERVER: process.env.SMTP_SERVER,
    SMTP_PORT: process.env.SMTP_PORT,
    AUTH_URL: process.env.AUTH_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    GROQ_API_KEY: process.env.GROQ_API_KEY,
    GROQ_API_ENDPOINT: process.env.GROQ_API_ENDPOINT,
    UNDRSTND_API_KEY: process.env.UNDRSTND_API_KEY,
    UNDRSTND_API_ENDPOINT: process.env.UNDRSTND_API_ENDPOINT,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GR_LPU_API_KEY_DEFAULT: process.env.GR_LPU_API_KEY_DEFAULT,
    CR_INF_API_KEY_DEFAULT: process.env.CR_INF_API_KEY_DEFAULT,
    SM_RDU_API_KEY_DEFAULT: process.env.SM_RDU_API_KEY_DEFAULT,
    NODE_ENV: process.env.NODE_ENV,
    PINECONE_API_KEY: process.env.PINECONE_API_KEY,
    PINECONE_API_ENDPOINT: process.env.PINECONE_API_ENDPOINT,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  },
})
